openapi: '3.0.0'
info: 
  title: documentation for group
  version: 1.0.0
  description: This is the documentation for group
paths: 


  /api/v1/group:
    post:
      summary: This endpoint is to create a group
      tags: [groups]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - groupname
                - contributionAmount
                - contributionFrequency
                - payoutFrequency
                - describeGroup
                - totalMembers
              properties:
                contributionAmount: 
                  type: string
                groupname: 
                  type: string
                contributionFrequency: 
                  type: string
                  enum: ['daily', 'weekly', 'monthly']
                payoutFrequency: 
                  type: string 
                  enum: ['daily', 'weekly', 'monthly']
                describeGroup:
                  type: string
                totalMembers:
                  type: number
      responses: 
        "201":
          description: group successfully created


    get:
      summary: This is to get all groups
      tags: [groups]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: successfully retrieved all groups




  /api/v1/group/groups:
    get:
      summary: This endpoint is to get one group
      parameters:
        - in: path
          name: id
      tags: [groups]
      security:
        - bearerAuth: []
      
      responses: 
        "201":
          description: group successfully created